### ISSUE TITLE
Implement 'From' trait instead of dedicate method 'from'

### ISSUE THREAD

**Issue by jayong93** [line/centraldogma-rs#8]
https://github.com/line/centraldogma-rs/blob/5b8b3e12c58a3631cb0e78a10ed699feab9019ac/src/model.rs#L52-L54

The method `from` above could be replaced with `impl From<i64> for Revision` and then we could use a fancy code like:
```rust
let rev: Revision = -1.into();
```

**Comment by ikhoon** [comment]
It looks nice. Are you interested in sending a PR?

**Comment by jayong93** [comment]
Sure, I'll create a PR soon.
